/************************************************/
/********* Author: Yousef Alaa *****************/
/********* Date  : 29/07/2026   *****************/
/********* File: Configuration File *****************/
/************************************************/

#ifndef  DIO_CONFIG_H
#define  DIO_CONFIG_H



#define DIO_PORTA_PIN0_DIR OUTPUT
#define DIO_PORTA_PIN1_DIR INPUT
#define DIO_PORTA_PIN2_DIR OUTPUT
#define DIO_PORTA_PIN3_DIR OUTPUT
#define DIO_PORTA_PIN4_DIR OUTPUT
#define DIO_PORTA_PIN5_DIR OUTPUT
#define DIO_PORTA_PIN6_DIR OUTPUT
#define DIO_PORTA_PIN7_DIR INTPUT

#define DIO_PORTB_PIN0_DIR OUTPUT
#define DIO_PORTB_PIN1_DIR INPUT
#define DIO_PORTB_PIN2_DIR OUTPUT
#define DIO_PORTB_PIN3_DIR OUTPUT
#define DIO_PORTB_PIN4_DIR OUTPUT
#define DIO_PORTB_PIN5_DIR OUTPUT
#define DIO_PORTB_PIN6_DIR OUTPUT
#define DIO_PORTB_PIN7_DIR INTPUT

#define DIO_PORTA_DIRECTIONS 0b##DIO_PORTA_PIN7_DIR##DIO_PORTA_PIN6_DIR##DIO_PORTA_PIN5_DIR##DIO_PORTA_PIN4_DIR##DIO_PORTA_PIN3_DIR##DIO_PORTA_PIN2_DIR## DIO_PORTA_PIN1_DIR  ## DIO_PORTA_PIN0_DIR
#define DIO_PORTA_DIRECTIONS CONC_BIT(DIO_PORTA_PIN7_DIR,DIO_PORTA_PIN6_DIR,DIO_PORTA_PIN5_DIR,DIO_PORTA_PIN4_DIR,DIO_PORTA_PIN3_DIR,DIO_PORTA_PIN2_DIR,DIO_PORTA_PIN1_DIR,DIO_PORTA_PIN0_DIR)

#endif